# @package _group_
- _target_: pytorch_lightning.loggers.NeptuneLogger
  project_name: ${general.workspace}/${general.project_name}
  experiment_name: ${general.experiment_name}
  offline_mode: false

- _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${general.save_dir}
  name: ${general.experiment_id}
  version: ${general.version}
