# @package _group_

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99999
  last_epoch: -1 # ${trainer.max_epochs}
  # need to set to number because of tensorboard logger
  # steps_per_epoch: -1

pytorch_lightning_params:
  interval: step
